### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by stasysp** [AlineKl/MachineLearning#1]
я бы не стала выбрасывать эти признаки [5], они не избыточны (например, бинарный признак наличия 18 лет точно имеет смысл), можно отбросить признаки на основании статистик, каких-нибудь боксплотов, распределений, доли объясненной вариации, значимости признаков в модели.
[23], вроде, не корректное выделение категориальных признаков (например, JobLevel и Education, должны быть категориальными, а выделились, как числовые)

**Comment by akladiev** [comment]
@stasysp Посмотри, пожалуйста) Исправила незаслуженно выкинутые признаки. Насчет [23] - обсуждала с Николаем Юрьевичем, признаки JobLevel и Education могут рассматриваться как числовые, т.к. они иерархичны (например, расстояние между первым и вторым уровнями образования будет меньше, чем между первым и четвертым)
